[theme]
base = "light"
primaryColor = "#3056D3"
backgroundColor = "#F7F7F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111110"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
